import {
  kpiFrameworkSchema,
  objectiveBlendSchema,
  type CampaignAgentState,
  type CreatorEvaluation,
  type CreatorMetricInputPayload,
  type FrameworkCreatorEvaluation,
  type FrameworkEvaluation,
  type KpiFramework,
  type MetricDefinition,
  type ObjectiveBlend,
  type ResolvedCampaignObjective,
  type WeightedMetric
} from "./schema";
import { createModel } from "./model";
import { defaultKpiFramework, errorMessage } from "./deterministicAnalysis";
import { normalizeInput } from "./objective";
import {
  compactCampaignSummaryForLlm,
  compactCreatorMetricsForLlm,
  compactNormalizedBriefForLlm,
  compactNiaContextForLlm,
  slimFrameworkEvaluationsForLlm
} from "./llmContextCompact";
import { cohortPerformanceTiersForScores, type PerformanceTier } from "./performanceTiering";
import { normalizeMetricValue } from "./scoringNormalization";

const OBJECTIVES: ResolvedCampaignObjective[] = ["awareness", "engagement", "sales"];

const METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  reach: {
    name: "reach",
    displayName: "Reach",
    definition: "The number of unique people exposed to the creator's campaign content.",
    whyItMatters: "Shows the scale of top-of-funnel visibility.",
    sourceMetricKeys: ["reach"]
  },
  impressions: {
    name: "impressions",
    displayName: "Impressions",
    definition: "The total number of times campaign content was shown.",
    whyItMatters: "Captures repeated exposure and awareness momentum.",
    sourceMetricKeys: ["impressions"]
  },
  completion_rate: {
    name: "completion_rate",
    displayName: "Completion Rate",
    definition: "The share of viewers who watched enough of the content to indicate attention quality.",
    whyItMatters: "Separates fleeting reach from content that actually held attention.",
    sourceMetricKeys: ["completionRate"]
  },
  share_velocity: {
    name: "share_velocity",
    displayName: "Share Velocity",
    definition: "How strongly audiences passed the content along through shares.",
    whyItMatters: "Signals amplification beyond the creator's owned audience.",
    sourceMetricKeys: ["shares"]
  },
  audience_penetration: {
    name: "audience_penetration",
    displayName: "Audience Penetration",
    definition: "How effectively campaign content reached the intended audience pool.",
    whyItMatters: "Helps determine whether awareness expanded in the right market.",
    sourceMetricKeys: ["reach", "audienceSegment"]
  },
  brand_sentiment: {
    name: "brand_sentiment",
    displayName: "Brand Sentiment",
    definition: "The direction and quality of audience reaction toward the brand.",
    whyItMatters: "Visibility only helps when it creates useful brand associations.",
    sourceMetricKeys: ["sentimentScore", "representativeComments"]
  },
  comment_depth: {
    name: "comment_depth",
    displayName: "Comment Depth",
    definition: "The volume and substance of comments generated by the content.",
    whyItMatters: "Shows whether audiences were moved to participate, ask, or react.",
    sourceMetricKeys: ["comments", "representativeComments"]
  },
  saves: {
    name: "saves",
    displayName: "Saves",
    definition: "The number of users who saved the content for later.",
    whyItMatters: "Indicates durable interest and future intent beyond a passive view.",
    sourceMetricKeys: ["saves"]
  },
  shares: {
    name: "shares",
    displayName: "Shares",
    definition: "The number of times users shared the content.",
    whyItMatters: "Reflects audience endorsement and community spread.",
    sourceMetricKeys: ["shares"]
  },
  engagement_quality: {
    name: "engagement_quality",
    displayName: "Engagement Quality",
    definition: "Active engagement relative to exposure, including likes, comments, shares, and saves.",
    whyItMatters: "Shows resonance quality instead of raw interaction volume.",
    sourceMetricKeys: ["likes", "comments", "shares", "saves", "impressions"]
  },
  sentiment: {
    name: "sentiment",
    displayName: "Sentiment",
    definition: "The positive or negative direction of audience response.",
    whyItMatters: "Helps distinguish useful engagement from noisy or negative conversation.",
    sourceMetricKeys: ["sentimentScore", "representativeComments"]
  },
  conversation_themes: {
    name: "conversation_themes",
    displayName: "Conversation Themes",
    definition: "The amount of audience discussion available for understanding what resonated.",
    whyItMatters: "Reveals what audiences are responding to and what needs clarification.",
    sourceMetricKeys: ["comments", "representativeComments"]
  },
  cta_intent: {
    name: "cta_intent",
    displayName: "CTA Intent",
    definition: "Audience movement from content toward a next action, approximated by click-through behavior.",
    whyItMatters: "Connects engagement with intent to continue through the funnel.",
    sourceMetricKeys: ["ctr"]
  },
  gmv: {
    name: "gmv",
    displayName: "GMV",
    definition: "Gross merchandise value attributed to the creator or campaign.",
    whyItMatters: "Directly measures commercial output.",
    sourceMetricKeys: ["gmv"]
  },
  conversion_rate: {
    name: "conversion_rate",
    displayName: "Conversion Rate",
    definition: "The rate at which qualified traffic converted into purchase behavior.",
    whyItMatters: "Shows whether attention and clicks translated into actual buying.",
    sourceMetricKeys: ["conversionRate"]
  },
  ctr: {
    name: "ctr",
    displayName: "Click-Through Rate",
    definition: "The share of viewers who clicked from content into the next funnel step.",
    whyItMatters: "Measures the creator's ability to create purchase intent.",
    sourceMetricKeys: ["ctr"]
  },
  add_to_cart: {
    name: "add_to_cart",
    displayName: "Add To Cart",
    definition: "The count of users who added the product to cart after creator exposure.",
    whyItMatters: "Captures mid-funnel buying intent before final conversion.",
    sourceMetricKeys: ["addToCart"]
  },
  cpa: {
    name: "cpa",
    displayName: "CPA Efficiency",
    definition: "Cost efficiency of acquiring a customer or desired action; lower is better.",
    whyItMatters: "Prevents raw sales volume from hiding inefficient spend.",
    sourceMetricKeys: ["cpa"]
  },
  roas: {
    name: "roas",
    displayName: "ROAS",
    definition: "Revenue returned for each unit of spend.",
    whyItMatters: "Balances revenue scale against budget efficiency.",
    sourceMetricKeys: ["roas"]
  },
  funnel_drop_off: {
    name: "funnel_drop_off",
    displayName: "Funnel Drop-Off",
    definition: "Where audiences lose momentum between attention, click, cart, and purchase.",
    whyItMatters: "Highlights the bottleneck that most limits business outcome.",
    sourceMetricKeys: ["ctr", "addToCart", "conversionRate"]
  }
};

const FRAMEWORK_GUIDANCE: Record<ResolvedCampaignObjective, string> = {
  awareness:
    "Evaluate reach quality, engagement density, amplification efficiency, consistency, and breakout potential. Do not treat sales outcomes as the main proof of awareness.",
  engagement:
    "Evaluate engagement quality, conversation depth, creator resonance, sustained interaction, and community amplification. Prioritize meaningful participation over passive reach.",
  sales:
    "Evaluate revenue efficiency, conversion strength, creator sales efficiency, sales consistency, and scalable growth potential. Prioritize efficient commercial outcomes over vanity metrics."
};

type Contribution = { name: string; score: number; weight: number };

function metricDefinitionFor(name: string): MetricDefinition {
  return (
    METRIC_DEFINITIONS[name] ?? {
      name,
      displayName: name.replace(/_/g, " ").replace(/\b\w/g, (char) => char.toUpperCase()),
      definition: "A campaign metric used by the selected scoring framework.",
      whyItMatters: "It contributes to the objective-specific performance grade.",
      sourceMetricKeys: [name]
    }
  );
}

function tierLabel(tier: "low" | "average" | "high"): string {
  if (tier === "high") return "High performer";
  if (tier === "average") return "Average performer";
  return "Low performer";
}

function evaluateCreatorForFramework(
  creator: CreatorMetricInputPayload,
  metrics: CreatorMetricInputPayload[],
  framework: KpiFramework
): Omit<FrameworkCreatorEvaluation, "performanceTier" | "tierRationale"> & { contributions: Contribution[] } {
  let weightedScore = 0;
  let appliedWeight = 0;
  const contributions: Contribution[] = [];
  const missingMetrics: string[] = [];

  for (const metric of framework.metrics) {
    const normalized = normalizeMetricValue(creator, metrics, metric.name);
    if (normalized === undefined) {
      missingMetrics.push(metric.name);
      continue;
    }

    weightedScore += normalized * metric.weight;
    appliedWeight += metric.weight;
    contributions.push({ name: metric.name, score: normalized, weight: metric.weight });
  }

  const score = appliedWeight > 0 ? Math.round(weightedScore / appliedWeight) : 0;
  const strongestMetrics = [...contributions]
    .filter((item) => item.score >= 65)
    .sort((a, b) => b.score * b.weight - a.score * a.weight)
    .slice(0, 3)
    .map((item) => item.name);
  const weakestMetrics = [...contributions]
    .filter((item) => item.score < 45)
    .sort((a, b) => a.score * b.weight - b.score * b.weight)
    .slice(0, 3)
    .map((item) => item.name);

  return {
    creatorName: creator.name,
    score,
    strongestMetrics,
    weakestMetrics,
    missingMetrics,
    confidence: missingMetrics.length > 1 ? "medium" : "high",
    contributions
  };
}

function frameworkTakeaways(
  objective: ResolvedCampaignObjective,
  evaluations: FrameworkCreatorEvaluation[]
): string[] {
  const top = [...evaluations].sort((a, b) => b.score - a.score)[0];
  if (!top) {
    return [`The ${objective} framework needs creator metrics before it can grade performance.`];
  }

  return [
    `${top.creatorName} is the strongest ${objective} performer in the supplied creator set.`,
    `${tierLabel(top.performanceTier)} label is driven by ${top.strongestMetrics[0] ?? "the available weighted signals"}.`,
    top.missingMetrics.length
      ? `Confidence is limited by missing ${top.missingMetrics.slice(0, 2).join(" and ")} data.`
      : `The ${objective} framework has enough tracked metrics for a directional read.`
  ];
}

async function generateFrameworkForObjective(
  state: CampaignAgentState,
  objective: ResolvedCampaignObjective
): Promise<{ framework: KpiFramework; errors: string[] }> {
  const normalizedBrief = state.normalizedBrief ?? normalizeInput(state);
  const fallback = defaultKpiFramework(objective, { ...normalizedBrief, objective }, Boolean(state.niaContext?.length));
  const model = createModel();
  if (!model) return { framework: fallback, errors: [] };

  try {
    const structuredModel = model.withStructuredOutput(kpiFrameworkSchema);
    const framework = await structuredModel.invoke([
      {
        role: "system",
        content:
          "You are a specialized CampaignOS framework agent. Return only a KPI framework matching the schema. Metric weights must sum to 100."
      },
      {
        role: "user",
        content: JSON.stringify({
          objective,
          frameworkGuidance: FRAMEWORK_GUIDANCE[objective],
          normalizedBrief: compactNormalizedBriefForLlm({ ...normalizedBrief, objective }),
          niaContext: compactNiaContextForLlm(state.niaContext ?? []),
          availableMetrics: compactCreatorMetricsForLlm(state.reacherMetrics ?? []),
          campaignSummary: compactCampaignSummaryForLlm(state.campaignSummary),
          defaultFramework: fallback
        })
      }
    ]);
    const totalWeight = framework.metrics.reduce((sum, metric) => sum + metric.weight, 0);
    return Math.round(totalWeight) === 100
      ? { framework: { ...framework, objective }, errors: [] }
      : { framework: fallback, errors: [`${objective} framework weights were invalid, so defaults were used.`] };
  } catch (error) {
    return {
      framework: fallback,
      errors: [`${objective} framework agent failed, so defaults were used: ${errorMessage(error)}`]
    };
  }
}

export async function runFrameworkAgents(state: CampaignAgentState): Promise<Partial<CampaignAgentState>> {
  const metrics = state.reacherMetrics ?? [];
  const errors: string[] = [];
  const frameworkEvaluations: FrameworkEvaluation[] = [];

  for (const objective of OBJECTIVES) {
    const generated = await generateFrameworkForObjective(state, objective);
    errors.push(...generated.errors);
    const draftedEvaluations = metrics.map((creator) => evaluateCreatorForFramework(creator, metrics, generated.framework));
    const frameworkTiers = cohortPerformanceTiersForScores(draftedEvaluations.map((item) => item.score));
    const creatorEvaluations = draftedEvaluations.map(({ contributions: _contributions, ...evaluation }, idx) => {
      const tier = frameworkTiers[idx]!;
      return {
        ...evaluation,
        performanceTier: tier,
        tierRationale: `${tierLabel(tier)} for ${objective}: ${evaluation.score}/100 vs ${metrics.length} creators in this set (tier is cohort-relative within the weighted ${objective} scorecard).`
      };
    });
    const campaignScore = creatorEvaluations.length
      ? Math.round(creatorEvaluations.reduce((sum, item) => sum + item.score, 0) / creatorEvaluations.length)
      : 0;

    frameworkEvaluations.push({
      objective,
      framework: generated.framework,
      metricDefinitions: generated.framework.metrics.map((metric) => metricDefinitionFor(metric.name)),
      campaignScore,
      creatorEvaluations,
      takeaways: frameworkTakeaways(objective, creatorEvaluations),
      confidence: creatorEvaluations.some((item) => item.confidence === "medium") ? "medium" : generated.framework.confidence
    });
  }

  const primaryFramework =
    frameworkEvaluations.find((item) => item.objective === state.normalizedBrief?.objective) ?? frameworkEvaluations[0];

  return {
    frameworkEvaluations,
    kpiFramework: primaryFramework?.framework,
    errors
  };
}

function defaultObjectiveBlend(primary: ResolvedCampaignObjective): ObjectiveBlend {
  const weights: ObjectiveBlend["weights"] = { awareness: 20, engagement: 20, sales: 20 };
  weights[primary] = 60;
  return {
    weights,
    rationale: `The campaign goal is primarily ${primary}, so that framework carries 60% of the composite grade while the other funnel signals remain visible at 20% each.`,
    confidence: "medium"
  };
}

function objectiveKeywordScore(text: string, objective: ResolvedCampaignObjective): number {
  const keywords: Record<ResolvedCampaignObjective, string[]> = {
    awareness: ["awareness", "reach", "views", "impressions", "visibility", "brand", "launch"],
    engagement: ["engagement", "comments", "saves", "shares", "community", "conversation", "resonance"],
    sales: ["sales", "gmv", "conversion", "purchase", "roas", "cpa", "shop", "revenue"]
  };
  return keywords[objective].reduce((score, keyword) => score + (text.includes(keyword) ? 1 : 0), 0);
}

function normalizeWeights(raw: Record<ResolvedCampaignObjective, number>): ObjectiveBlend["weights"] {
  const positive = OBJECTIVES.map((objective) => Math.max(0, raw[objective] || 0));
  const total = positive.reduce((sum, value) => sum + value, 0);
  if (total <= 0) return { awareness: 34, engagement: 33, sales: 33 };

  const rounded = OBJECTIVES.map((objective, index) => ({
    objective,
    weight: Math.round((positive[index] / total) * 100)
  }));
  const delta = 100 - rounded.reduce((sum, item) => sum + item.weight, 0);
  rounded[0] = { ...rounded[0]!, weight: rounded[0]!.weight + delta };

  return {
    awareness: rounded.find((item) => item.objective === "awareness")?.weight ?? 0,
    engagement: rounded.find((item) => item.objective === "engagement")?.weight ?? 0,
    sales: rounded.find((item) => item.objective === "sales")?.weight ?? 0
  };
}

function deterministicObjectiveBlend(state: CampaignAgentState): ObjectiveBlend {
  const normalizedBrief = state.normalizedBrief ?? normalizeInput(state);
  const text = [
    normalizedBrief.objective,
    normalizedBrief.brief,
    normalizedBrief.product,
    normalizedBrief.audience,
    ...normalizedBrief.kpiPriorities,
    ...(state.niaContext ?? []).map((item) => item.excerpt)
  ]
    .join(" ")
    .toLowerCase();

  const raw: Record<ResolvedCampaignObjective, number> = { awareness: 20, engagement: 20, sales: 20 };
  raw[normalizedBrief.objective] += 40;
  for (const objective of OBJECTIVES) {
    raw[objective] += objectiveKeywordScore(text, objective) * 5;
  }

  const metrics = state.reacherMetrics ?? [];
  if (metrics.some((item) => item.gmv !== undefined || item.conversionRate !== undefined || item.roas !== undefined)) {
    raw.sales += 10;
  }
  if (metrics.some((item) => item.comments !== undefined || item.saves !== undefined || item.shares !== undefined)) {
    raw.engagement += 8;
  }
  if (metrics.some((item) => item.reach !== undefined || item.impressions !== undefined)) {
    raw.awareness += 8;
  }
  if (state.campaignSummary?.totalOrders !== undefined) raw.sales += 6;
  if (
    state.campaignSummary?.totalLikes !== undefined ||
    state.campaignSummary?.totalComments !== undefined ||
    state.campaignSummary?.avgEngagementRate !== undefined
  ) {
    raw.engagement += 6;
  }
  if (state.campaignSummary?.totalViews !== undefined || state.campaignSummary?.avgDailyViews !== undefined) {
    raw.awareness += 6;
  }

  const weights = normalizeWeights(raw);
  return {
    weights,
    rationale:
      `The goal mix was inferred from the ${normalizedBrief.objective} campaign objective, KPI priorities, Nia context, and which funnel metrics were available.`,
    confidence: state.niaContext?.length ? "high" : "medium"
  };
}

export async function calculateObjectiveBlend(state: CampaignAgentState): Promise<Partial<CampaignAgentState>> {
  const fallback = deterministicObjectiveBlend(state);
  const model = createModel();
  if (!model) return { objectiveBlend: fallback };

  try {
    const structuredModel = model.withStructuredOutput(objectiveBlendSchema);
    const briefForPrompt = compactNormalizedBriefForLlm(state.normalizedBrief ?? normalizeInput(state));
    const blend = await structuredModel.invoke([
      {
        role: "system",
        content:
          "Calculate the CampaignOS objective goal mix. Weights for awareness, engagement, and sales must sum to 100. Use the campaign goal, KPI priorities, context, observed metric availability, and slim framework summaries."
      },
      {
        role: "user",
        content: JSON.stringify({
          normalizedBrief: briefForPrompt,
          niaContext: compactNiaContextForLlm(state.niaContext ?? []),
          metrics: compactCreatorMetricsForLlm(state.reacherMetrics ?? []),
          campaignSummary: compactCampaignSummaryForLlm(state.campaignSummary),
          frameworkEvaluationsSlim: slimFrameworkEvaluationsForLlm(state.frameworkEvaluations ?? []),
          deterministicFallback: fallback
        })
      }
    ]);

    const total = blend.weights.awareness + blend.weights.engagement + blend.weights.sales;
    if (Math.round(total) !== 100) {
      return { objectiveBlend: fallback, errors: ["Objective blend weights were invalid, so deterministic weights were used."] };
    }
    return { objectiveBlend: blend };
  } catch (error) {
    return {
      objectiveBlend: fallback,
      errors: [`Objective blend agent failed, so deterministic weights were used: ${errorMessage(error)}`]
    };
  }
}

function recommendedCreatorAction(objective: ResolvedCampaignObjective, creatorName: string, tier: PerformanceTier): string {
  if (tier === "high") return `Scale ${creatorName} with more budget or additional content variations.`;
  if (objective === "sales") return `Tighten CTA and product proof points before scaling ${creatorName}.`;
  if (objective === "engagement") return `Give ${creatorName} prompts that invite comments, saves, and shares.`;
  return `Improve the first three seconds and brand cue clarity for ${creatorName}.`;
}

export function blendFrameworkScores(state: CampaignAgentState): Partial<CampaignAgentState> {
  const objectiveBlend = state.objectiveBlend ?? defaultObjectiveBlend(state.normalizedBrief?.objective ?? "awareness");
  const frameworkEvaluations = state.frameworkEvaluations ?? [];
  const creatorNames = new Set<string>();

  for (const framework of frameworkEvaluations) {
    for (const creator of framework.creatorEvaluations) creatorNames.add(creator.creatorName);
  }

  const draftedComposite = [...creatorNames].map((creatorName) => {
    let weightedScore = 0;
    let appliedWeight = 0;
    const strongest: Array<{ objective: ResolvedCampaignObjective; metric: string; weight: number }> = [];
    const weakest: Array<{ objective: ResolvedCampaignObjective; metric: string; weight: number }> = [];
    const missing = new Set<string>();

    for (const framework of frameworkEvaluations) {
      const weight = objectiveBlend.weights[framework.objective];
      const creator = framework.creatorEvaluations.find((item) => item.creatorName === creatorName);
      if (!creator || weight <= 0) continue;

      weightedScore += creator.score * weight;
      appliedWeight += weight;
      for (const metric of creator.strongestMetrics) strongest.push({ objective: framework.objective, metric, weight });
      for (const metric of creator.weakestMetrics) weakest.push({ objective: framework.objective, metric, weight });
      for (const metric of creator.missingMetrics) missing.add(metric);
    }

    const score = appliedWeight > 0 ? Math.round(weightedScore / appliedWeight) : 0;
    const primaryDriver =
      strongest.sort((a, b) => objectiveBlend.weights[b.objective] - objectiveBlend.weights[a.objective])[0];
    const primaryDrag = weakest.sort((a, b) => objectiveBlend.weights[b.objective] - objectiveBlend.weights[a.objective])[0];
    const confidence: FrameworkCreatorEvaluation["confidence"] = missing.size > 2 ? "medium" : "high";

    return {
      creatorName,
      score,
      strongest,
      weakest,
      missing,
      primaryDriver,
      primaryDrag,
      confidence
    };
  });

  const compositeTiers = cohortPerformanceTiersForScores(draftedComposite.map((row) => row.score));

  const creatorEvaluations: CreatorEvaluation[] = draftedComposite
    .map((row, index) => {
      const performanceTier = compositeTiers[index]!;
      return {
        creatorName: row.creatorName,
        score: row.score,
        rank: 1,
        performanceTier,
        tierRationale: `${tierLabel(performanceTier)} on the blended goal mix (awareness ${objectiveBlend.weights.awareness}%, engagement ${objectiveBlend.weights.engagement}%, sales ${objectiveBlend.weights.sales}%) — tiers are cohort-relative among ${creatorNames.size} creators.`,
        strengths: row.strongest.length
          ? row.strongest.slice(0, 3).map((item) => `${item.metric} supported the ${item.objective} framework`)
          : ["Performance was directionally balanced across available frameworks."],
        weaknesses: [
          ...row.weakest.slice(0, 2).map((item) => `${item.metric} limited the ${item.objective} framework`),
          ...[...row.missing].slice(0, 2).map((metric) => `${metric} was missing`)
        ],
        primaryDriver: row.primaryDriver ? `${row.primaryDriver.objective}:${row.primaryDriver.metric}` : "insufficient data",
        primaryDrag: row.primaryDrag ? `${row.primaryDrag.objective}:${row.primaryDrag.metric}` : "insufficient data",
        recommendedAction: recommendedCreatorAction(state.normalizedBrief?.objective ?? "awareness", row.creatorName, performanceTier),
        confidence: row.confidence
      } satisfies CreatorEvaluation;
    })
    .sort((a, b) => b.score - a.score)
    .map((evaluation, index) => ({ ...evaluation, rank: index + 1 }));

  return { creatorEvaluations, objectiveBlend };
}

export function metricDefinitionsFor(metrics: WeightedMetric[]): MetricDefinition[] {
  return metrics.map((metric) => metricDefinitionFor(metric.name));
}
